### ISSUE TITLE
Login with Spotify link is broken.

### ISSUE THREAD

**Issue by felipesousa** [tsirlucas/soundplace#69]
When I click on "Conecte-se com o Spotify" button, I'm redirected to `https://soundplace-api.herokuapp.com//auth/spotify` link, the link is broken.

Link to image preview: {https://ibb.co/f67zLT}

If use `/` instead of `//` the page is loaded correctly :)

**Comment by tsirlucas** [comment]
MB, I'm setting up travis again (the project was kinda dead) and set an env var wrongly.

**Comment by tsirlucas** [comment]
It's fixed, please update SW and try again.
